apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-persistent-volume-claim
spec:
  accessModes:
    #  can only be used by one pod
    - ReadWriteOnce
  resources:
    requests:
      # can be in gigabytes - 1Gi - or megabytes - see below
      storage: 50Mi
