apiVersion: apps/v1
# Object type
kind: Deployment
# name of Object
metadata:
  name: redis-deployment
spec:
  # number of pods from template
  replicas: 1
  # this object will look for this specific selector
  selector:
    matchLabels:
      component: redis
  # configuration of pod
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            # port to open the client image
            - containerPort: 6379
