apiVersion: apps/v1
# Object type
kind: Deployment
# name of Object
metadata:
  name: server-deployment
spec:
  # number of pods from template
  replicas: 3
  # this object will look for this specific selector
  selector:
    matchLabels:
      component: server
  # configuration of pod
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: giorgiosavron/fibapp-server
          ports:
            # port to open the client image
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redis-cluster-ip-service
            - name: REDIS_PORT
              value: "6379"
            - name: PGUSER
              value: postgres
            - name: PGHOST
              value: postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
